Проверка заданий
js-tasks-ru/vue-20240924_vacys1337 pull request #2
Opened 2024-10-06 18:38 UTC by glo1337

Реализованы задачи из блоков:
Основы: Часть 1,
Основы: Часть 2

2024-10-06 18:39 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-06 18:41 UTC, ShGKme requested changes
Требуется небольшое исправление. Остальные задачи приняты

2024-10-06 18:41 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +        const dateString = new Date().toLocaleDateString('en-EN', {
Вместо фиксированной локализации (`en-EN` или `ru-RU`) лучше всегда использовать `navigator.language`. Так локализация всегда будет той, что пользователь выбрал в настройках своего браузера.

2024-10-06 18:41 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +    watch([currentOperation, firstOperand, secondOperand], calculateResult);
Здесь через отслеживание вручную реализовано вычисление `calculationResult` при изменении любой из зависимостей вычисления. Фактически реализовано вычисляемое свойство, но вручную. Такие свойства нужно реализовывать именно как вычисляемое свойство `computed`:

- Это явно. Так `result` будет описан именно как вычисляемый, а не как самостоятельная переменная с собственным значением
- Не нужно самостоятельно определять зависимости отслеживания и контролировать корректность списка зависимостей
- Эффективнее - вычисляемые свойства ленивые и вычисляются только, когда к их значению обращаются

2024-10-07 06:00 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-07 06:13 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-07 06:14 UTC, glo1337 commented
Григорий, доброго времени суток!
Спасибо за рекомендации по исправлению в задачах, я внёс изменения

2024-10-07 17:49 UTC, ShGKme approved these changes

2024-10-07 17:51 UTC, merged